### ISSUE TITLE
Pending Features

### ISSUE THREAD

**Issue by Spelunkern** [Spelunkern/Shaiya-Essentials#1]
An small list with several requested or useful features to complete/upgrade the project.
It will remain here just as a reminder, it doesn't mean they are gonna get support or they will be ever done.

To-do list:

**Feature / Notes**

~-Mob Colors Range .~
~-x10 skillpoints.~
~-NPC runes - Uses effect 200 and variant as a Npc type definition.~ _(Discarded)_
~-Effects function - Uses a parameter of an equipped item to enable effects on char.~ (Vanilla aura avaliable, no further support)
~-Titles - Same as effects function but for displaying the feature know as 'Titles'.~  (Vanilla title avaliable, no further support)
~-Color function - Same as other functions but for changing the color of the user name.~
-Weapon Skins - Support for weapon skin slot.
-Raid capacity - Support for bigger raid capacity, server side already released.
~-More skills bar - Support for more skills bars.~

**Comment by kurtekat** [comment]
> -NPC runes - Uses effect 200 and variant as a Npc type definition.

This appears to be the same as warehouse recall runes. I'm pretty sure this is a client-side feature that isn't supported by our game.exe. Of course, I can't possibly know that for sure. The items/skills work as expected.

**Comment by Spelunkern** [comment]
Yeah it seems as a removed feature over time, it started on some ep 5.4 PT clients and remains in some EP6 ones. A similar situation with the transfer cube surely.
